In [1]:
import torch
import numpy
import pandas as pd
import sklearn
print(torch.__version__)
print(torch.cuda.is_available())
print(f"Using Scikit-Learn version: {sklearn.__version__} (materials in this guide require this version or newer).")

1.12.1+cu113
True
Using Scikit-Learn version: 1.5.1 (materials in this guide require this version or newer).


In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [3]:
print(x_data.device)
shape=(2,3,)
rt=torch.rand(shape)
print(rt)
print(rt.dtype)

cpu
tensor([[0.8123, 0.2652, 0.5594],
        [0.8289, 0.3088, 0.9669]])
torch.float32


In [4]:
t1=torch.cat([rt,rt,rt],dim=1)#default dim=0
print(t1)

tensor([[0.8123, 0.2652, 0.5594, 0.8123, 0.2652, 0.5594, 0.8123, 0.2652, 0.5594],
        [0.8289, 0.3088, 0.9669, 0.8289, 0.3088, 0.9669, 0.8289, 0.3088, 0.9669]])


In [10]:
#matrix multiplication
y1=rt@rt.T
y2=rt.matmul(rt.T)
y3 = torch.rand(2,2)
torch.matmul(rt,rt.T,out=y3)
print(y1,y2,y3)
#element-wise
z1=rt*rt
z2=rt.mul(rt)
z3 = torch.rand_like(z1)
torch.mul(rt,rt,out=z3)
print(z1,z2,z3)

tensor([[1.0430, 1.2960],
        [1.2960, 1.7173]]) tensor([[1.0430, 1.2960],
        [1.2960, 1.7173]]) tensor([[1.0430, 1.2960],
        [1.2960, 1.7173]])
tensor([[0.6598, 0.0704, 0.3129],
        [0.6871, 0.0953, 0.9349]]) tensor([[0.6598, 0.0704, 0.3129],
        [0.6871, 0.0953, 0.9349]]) tensor([[0.6598, 0.0704, 0.3129],
        [0.6871, 0.0953, 0.9349]])


In [13]:
#Single-element tensors
sum=y1.sum()
si=sum.item()
print(sum, type(sum),si,type(si))

tensor(5.3523) <class 'torch.Tensor'> 5.352318286895752 <class 'float'>


In [15]:
#In-place operations _
print(y1.add_(5))

tensor([[6.0430, 6.2960],
        [6.2960, 6.7173]])


In [18]:
# numpy change with tensor
n1=y1.numpy()
print(n1)
y1.add_(-5)
print(n1)

[[1.0429955 1.2960143]
 [1.2960143 1.7172942]]
[[-3.9570045 -3.7039857]
 [-3.7039857 -3.2827058]]


In [29]:
# tensor change with numpy
np=numpy.ones((3,4))
t2=torch.from_numpy(np)
numpy.add(np,1,out=np)
print(np)
print(t2)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)


In [37]:
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

TypeError: unsupported operand type(s) for -: 'str' and 'str'